(defvar NOTE-TABLE)

(setf NOTE-TABLE '((C 1) 
                   (C-SHARP 2) 
                   (D 3) 
                   (D-SHARP 4) 
                   (E 5) 
                   (F 6) 
                   (F-SHARP 7) 
                   (G 8) 
                   (G-SHARP 9) 
                   (A 10) 
                   (A-SHARP 11) 
                   (B 12)))
