(defun space-over (n) 
  (cond ((< n 0) 
         (format t "Error!"))
        ((= n 0) (format t ""))
        (t (format t " ") (space-over (- n 1)))))

(defun test (n) 
  (format t "-%>>>") 
  (space-over n) 
  (format t "<<<"))
