(setf ROOMS '((living-room nil) 
      (upstairs-bedroom nil) 
      (dining-room nil) 
      (kitchen nil) 
      (pantry nil) 
      (downstairs-bedroom nil) 
      (back=stairs nil)
      (front-stairs nil)
      (library nil)))
