(defvar ROOMS)

(setf ROOMS '((living-room (north front-stairs) (south dining-room)
              (east kitchen)) 
              (upstairs-bedroom nil) 
              (dining-room nil) 
              (kitchen nil) 
              (pantry nil) 
              (downstairs-bedroom nil) 
              (back=stairs nil)
              (front-stairs nil)
              (library nil)))
