(define computer "a machine that runs programs")
(define hardware "")
(define software "")
(define operating-system "")
(define compiler "")
(define database-management-system "")
(define artificial-intelligence "")
(define soft-computing "")
(define graphics "")
