(def computer "a machine that runs programs")
(def hardware "")
(def software "")
(def operating-system "")
(def compiler "")
(def database-management-system "")
(def artificial-intelligence "")
(def soft-computing "")
(def graphics "")
